name: python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "nomad-lab>=0.10.1"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 *parser tests
    - name: pylint
      run: |
        python -m pylint --load-plugins=nomad.metainfo.pylint_plugin *parser tests
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional *parser tests
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
